[FSK-16]: Configure Cypress
fullstacksjs/the-charity pull request #13
Opened 2022-09-05 17:28 UTC by erfan-goodarzi

This PR adds cypress configuration.

2022-09-07 09:15 UTC, AmirabbasJ commented
@erfan-goodarzi @ASafaeirad 
I've had to downgrade nodejs because of [this](https://github.com/cypress-io/cypress/issues/22795#issuecomment-1225535244) and [this](https://github.com/cypress-io/cypress/issues/23499#issuecomment-1224214313)

2022-09-07 15:10 UTC, AmirabbasJ requested changes

2022-09-07 15:10 UTC, AmirabbasJ commented on .github/workflows/CI.yml
> +        uses: actions/checkout@v2
why not v3?

```suggestion
        uses: actions/checkout@v3
```

2022-09-07 15:10 UTC, AmirabbasJ commented on .github/workflows/CI.yml
> -      - dev
why did you delete these lines?

2022-09-07 15:10 UTC, AmirabbasJ commented on package.json
> +    "test:e2e:run": "start-server-and-test ru http://127.0.0.1:5173 cy:e2e:run",
is there typo in this line?

2022-09-07 17:31 UTC, ASafaeirad commented on .gitignore
> -*.sw?
Seems the line ending is changed here

2022-09-07 17:50 UTC, AmirabbasJ commented on .github/workflows/CI.yml
> +
you mean not run it?

2022-09-08 00:27 UTC, ASafaeirad commented on .github/workflows/CI.yml
> +
That trailing space on line 31.

2022-09-08 11:28 UTC, AmirabbasJ commented on .github/workflows/CI.yml
> +
I don't know maybe we could have a yaml linter to lint all our yaml files

2022-09-09 10:01 UTC, AmirabbasJ commented
@erfan-goodarzi  do a rebase with dev before merging

2022-09-09 10:02 UTC, AmirabbasJ approved these changes

2022-09-09 11:21 UTC, merged