[FSK-13] : Configure react-location
fullstacksjs/the-charity pull request #3
Opened 2022-09-01 07:02 UTC by erfan-goodarzi

This PR add React location to project.

2022-09-01 08:48 UTC, AmirabbasJ commented on src/App.tsx
> +
```suggestion

const location = new ReactLocation();
```

I think it's a better idea we put this outside of app 
what you think?

2022-09-01 08:48 UTC, AmirabbasJ commented on src/App.tsx
> +  );
```suggestion
  return (
     <Router routes={[{ path: '/' }]} location={location}>
        The Charity App
    </Router>
  );
```

why not do this instead?
we get rid of the wrapping `<> ... </>` plus I've seen them doing it this way 
what are your thoughts?

2022-09-01 08:56 UTC, AmirabbasJ requested changes

2022-09-01 08:56 UTC, AmirabbasJ commented on src/App.tsx
> +  );
```suggestion
  return (
     <Router routes={[{ path: '/' }]} location={location}>
        The Charity App
    </Router>
  );
```

why not do this instead?
we get rid of the wrapping `<> ... </>` plus I've seen them doing it this way 
what are your thoughts?

2022-09-01 08:56 UTC, AmirabbasJ commented on src/App.tsx
> +
```suggestion

const location = new ReactLocation();
```

I think it's a better idea if we put this outside of app 
what you think?

2022-09-01 10:21 UTC, AmirabbasJ commented on src/App.tsx
> +  );
like what exactly?
I don't think we have anything as a sibling in the app, maybe just a wrapper

2022-09-01 11:03 UTC, AmirabbasJ commented
And one thing to note that this merge should happen after #2 
so I'd say even after getting approved, you wait till that pull request is merged, then pull the updates to this branch
and then merge it

2022-09-02 13:27 UTC, ASafaeirad commented
#2 is merged

2022-09-02 13:44 UTC, merged